# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Food.create!(name: "鶏胸肉（皮なし）", protein: 31, fat: 3.6, carbohydrate: 0, favorite: 0)
Food.create!(name: "牛ヒレ肉", protein: 36.1, fat: 5, carbohydrate: 0, favorite: 0)
Food.create!(name: "マグロ（赤身）", protein: 25.4, fat: 1, carbohydrate: 0, favorite: 0)
Food.create!(name: "鮭", protein: 25.4, fat: 8.3, carbohydrate: 0, favorite: 0)
Food.create!(name: "卵", protein: 13, fat: 10, carbohydrate: 1.1, favorite: 0)
Food.create!(name: "大豆", protein: 16.6, fat: 9.4, carbohydrate: 30, favorite: 0)
Food.create!(name: "豆腐", protein: 8.1, fat: 4.2, carbohydrate: 2, favorite: 0)
Food.create!(name: "鰹", protein: 25.8, fat: 1, carbohydrate: 0, favorite: 0)
Food.create!(name: "えび", protein: 20.9, fat: 0.4, carbohydrate: 0.2, favorite: 0)
Food.create!(name: "かに", protein: 19.4, fat: 1.5, carbohydrate: 0.5, favorite: 0)
Food.create!(name: "牛レバー", protein: 20.6, fat: 3.9, carbohydrate: 3.3, favorite: 0)
Food.create!(name: "鶏ささみ", protein: 22.5, fat: 1.3, carbohydrate: 0, favorite: 0)
Food.create!(name: "鮪の白身", protein: 29.9, fat: 4.2, carbohydrate: 0, favorite: 0)
Food.create!(name: "豚ヒレ肉", protein: 22.2, fat: 3, carbohydrate: 0, favorite: 0)
Food.create!(name: "ツナ缶（水煮）", protein: 24.8, fat: 0.7, carbohydrate: 0.1, favorite: 0)
Food.create!(name: "サバ", protein: 21.7, fat: 12, carbohydrate: 0, favorite: 0)
Food.create!(name: "鶏レバー", protein: 17.6, fat: 4, carbohydrate: 0, favorite: 0)
Food.create!(name: "イカ", protein: 18.1, fat: 0.8, carbohydrate: 1.5, favorite: 0)
Food.create!(name: "ほたて貝", protein: 16.6, fat: 0.8, carbohydrate: 0.1, favorite: 0)
Food.create!(name: "ヨーグルト（ギリシャ）|", protein: 10, fat: 0.4, carbohydrate: 3.6, favorite: 0)
Food.create!(name: "アボカド", protein: 2, fat: 15, carbohydrate: 9, favorite: 0)
Food.create!(name: "オリーブオイル", protein: 0, fat: 100, carbohydrate: 0, favorite: 0)
Food.create!(name: "ナッツミックス", protein: 15, fat: 50, carbohydrate: 20, favorite: 0)
Food.create!(name: "クルミ", protein: 15, fat: 65, carbohydrate: 14, favorite: 0)
Food.create!(name: "アーモンド", protein: 21.2, fat: 49.4, carbohydrate: 21.7, favorite: 0)
Food.create!(name: "ピーナッツ", protein: 25.8, fat: 49.2, carbohydrate: 16.1, favorite: 0)
Food.create!(name: "マヨネーズ", protein: 1, fat: 75, carbohydrate: 1, favorite: 0)
Food.create!(name: "バター", protein: 0.9, fat: 81, carbohydrate: 0.1, favorite: 0)
Food.create!(name: "ココナッツ", protein: 3.3, fat: 33.5, carbohydrate: 15.2, favorite: 0)
Food.create!(name: "チーズ（チェダー）|", protein: 24, fat: 33, carbohydrate: 1.3, favorite: 0)
Food.create!(name: "カシューナッツ", protein: 18.2, fat: 43.9, carbohydrate: 30.2, favorite: 0)
Food.create!(name: "パルメザンチーズ", protein: 35, fat: 25.8, carbohydrate: 3.2, favorite: 0)
Food.create!(name: "ゴマ", protein: 17.7, fat: 48, carbohydrate: 23.5, favorite: 0)
Food.create!(name: "サーモン（サーモン）|", protein: 20.4, fat: 13.4, carbohydrate: 0, favorite: 0)
Food.create!(name: "ラード", protein: 0, fat: 100, carbohydrate: 0, favorite: 0)
Food.create!(name: "ココナッツオイル", protein: 0, fat: 100, carbohydrate: 0, favorite: 0)
Food.create!(name: "ピスタチオ", protein: 20.2, fat: 45.4, carbohydrate: 27.2, favorite: 0)
Food.create!(name: "マカダミアナッツ", protein: 7.9, fat: 75.8, carbohydrate: 13.8, favorite: 0)
Food.create!(name: "ブラジルナッツ", protein: 14.3, fat: 66.4, carbohydrate: 12.3, favorite: 0)
Food.create!(name: "ダックファット", protein: 0, fat: 100, carbohydrate: 0, favorite: 0)
Food.create!(name: "玄米", protein: 7.5, fat: 2.7, carbohydrate: 77.2, favorite: 0)
Food.create!(name: "オートミール", protein: 13, fat: 7, carbohydrate: 68.5, favorite: 0)
Food.create!(name: "パスタ（乾燥）", protein: 12.5, fat: 1.5, carbohydrate: 75, favorite: 0)
Food.create!(name: "白米", protein: 6.7, fat: 0.5, carbohydrate: 80, favorite: 0)
Food.create!(name: "じゃがいも", protein: 2, fat: 0.1, carbohydrate: 17, favorite: 0)
Food.create!(name: "さつまいも", protein: 1.2, fat: 0.3, carbohydrate: 27.9, favorite: 0)
Food.create!(name: "バナナ", protein: 1.3, fat: 0.3, carbohydrate: 23, favorite: 0)
Food.create!(name: "小麦粉", protein: 10, fat: 1.5, carbohydrate: 73, favorite: 0)
Food.create!(name: "黒パン", protein: 8.5, fat: 2, carbohydrate: 51, favorite: 0)
Food.create!(name: "とうもろこし", protein: 3.2, fat: 1.2, carbohydrate: 19, favorite: 0)
Food.create!(name: "うどん", protein: 8, fat: 1, carbohydrate: 62.5, favorite: 0)
Food.create!(name: "おもち", protein: 6.8, fat: 0.8, carbohydrate: 49.7, favorite: 0)
Food.create!(name: "食パン", protein: 9, fat: 3.9, carbohydrate: 47, favorite: 0)
Food.create!(name: "クスクス", protein: 12.8, fat: 0.6, carbohydrate: 77.4, favorite: 0)
Food.create!(name: "大麦", protein: 10, fat: 2.5, carbohydrate: 73.5, favorite: 0)
Food.create!(name: "ライ麦", protein: 9.8, fat: 1.9, carbohydrate: 57, favorite: 0)
Food.create!(name: "エンドウ豆", protein: 5.5, fat: 0.4, carbohydrate: 21.7, favorite: 0)
Food.create!(name: "乾燥そば", protein: 13, fat: 3, carbohydrate: 72, favorite: 0)
Food.create!(name: "ビーンズ（缶詰）", protein: 7.8, fat: 0.5, carbohydrate: 27.5, favorite: 0)
Food.create!(name: "クッキー", protein: 5.7, fat: 20, carbohydrate: 70, favorite: 0)
